spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api